exp_name: control_icot-math-1-1
trainer:
  run_name: control_icot-math-1-1
  output_dir: saved_models/math/control_icot-1-1
  overwrite_output_dir: true
  bf16: true
  tf32: true
  report_to: 'tensorboard'
  seed: 42
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 32
  num_train_epochs: 1
  optim: 'adamw_torch'
  weight_decay: 0.01
  lr_scheduler_type: 'cosine_with_min_lr'
  learning_rate: 2e-5
  lr_scheduler_kwargs:
    min_lr_rate: 0.1
  warmup_ratio: 0.1
  save_strategy: 'no'
  ddp_find_unused_parameters: false
  logging_steps: 10
  dataloader_num_workers: 0

model:
  model_path: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'

data:
  data_path: 'synthesized_data/math/control_icot.jsonl'
  train_data_path: 'synthesized_data/math/control_icot.jsonl'
  tokenizer_path: ${model.model_path}
  model_max_length: 4352
  max_src_len: 256
  max_tgt_len: 4096




